(* Created with the Wolfram Language : www.wolfram.com *)
TopologyList[Process -> {V[1]} -> {F[3, {2, Index[Colour, 2]}], 
     -F[3, {2, Index[Colour, 3]}], F[4, {3, Index[Colour, 4]}], 
     -F[4, {3, Index[Colour, 5]}]}, Model -> {"SMQCD"}, 
  GenericModel -> {"Lorentz"}, InsertionLevel -> {Particles}, 
  ExcludeParticles -> {S[1], S[2], -S[3], S[3], V[1], V[2], -V[3], V[3]}, 
  ExcludeFieldPoints -> {}, LastSelections -> {}][
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> F[3, {2, Index[Colour, 6]}], 
      Field[10] -> -F[3, {2, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[3, {2, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[4, {3, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[3, {2, Index[Colour, 6]}], Field[9] -> -F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[3, {2, Index[Colour, 6]}], Field[9] -> -F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[4, {3, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> 
       -F[4, {3, Index[Colour, 7]}], Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> 
       -F[4, {3, Index[Colour, 7]}], Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> F[4, {3, Index[Colour, 6]}], 
      Field[10] -> -F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[4, {3, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[4, {3, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[3, {1, Index[Colour, 6]}], 
      Field[9] -> F[3, {1, Index[Colour, 6]}], Field[10] -> 
       -F[3, {1, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 2][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[3, {2, Index[Colour, 6]}], 
      Field[9] -> F[3, {2, Index[Colour, 6]}], Field[10] -> 
       -F[3, {2, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 3][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[3, {3, Index[Colour, 6]}], 
      Field[9] -> F[3, {3, Index[Colour, 6]}], Field[10] -> 
       -F[3, {3, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 4][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[3, {1, Index[Colour, 6]}], 
      Field[9] -> -F[3, {1, Index[Colour, 6]}], 
      Field[10] -> F[3, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[3, {2, Index[Colour, 6]}], 
      Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[3, {3, Index[Colour, 6]}], 
      Field[9] -> -F[3, {3, Index[Colour, 6]}], 
      Field[10] -> F[3, {3, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 7][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[4, {1, Index[Colour, 6]}], 
      Field[9] -> F[4, {1, Index[Colour, 6]}], Field[10] -> 
       -F[4, {1, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 8][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[4, {2, Index[Colour, 6]}], 
      Field[9] -> F[4, {2, Index[Colour, 6]}], Field[10] -> 
       -F[4, {2, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 9][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> -F[4, {3, Index[Colour, 6]}], 
      Field[9] -> F[4, {3, Index[Colour, 6]}], Field[10] -> 
       -F[4, {3, Index[Colour, 7]}]], FeynmanGraph[1, Particles == 10][
      Field[1] -> V[1], Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[4, {1, Index[Colour, 6]}], 
      Field[9] -> -F[4, {1, Index[Colour, 6]}], 
      Field[10] -> F[4, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 11][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[4, {2, Index[Colour, 6]}], 
      Field[9] -> -F[4, {2, Index[Colour, 6]}], 
      Field[10] -> F[4, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 12][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       V[5, {Index[Gluon, 7]}], Field[8] -> F[4, {3, Index[Colour, 6]}], 
      Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[6]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       -F[4, {3, Index[Colour, 6]}], Field[8] -> 
       -F[4, {3, Index[Colour, 7]}], Field[9] -> F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[4, {3, Index[Colour, 6]}], Field[8] -> F[4, {3, Index[Colour, 7]}], 
      Field[9] -> -F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[4, {3, Index[Colour, 6]}], Field[8] -> -F[4, {3, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[4, {3, Index[Colour, 6]}], Field[8] -> -F[4, {3, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       -F[4, {3, Index[Colour, 6]}], Field[8] -> F[4, {3, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       -F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> V[5, {Index[Gluon, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> -F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> -F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       -F[3, {2, Index[Colour, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 7]}], Field[9] -> F[3, {2, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[8]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[3, {2, Index[Colour, 6]}], Field[8] -> F[3, {2, Index[Colour, 7]}], 
      Field[9] -> -F[3, {2, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[3, {2, Index[Colour, 6]}], Field[8] -> -F[3, {2, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       V[5, {Index[Gluon, 8]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       F[3, {2, Index[Colour, 6]}], Field[8] -> -F[3, {2, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       F[3, {2, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][9], Field[5]], 
   Propagator[Internal][Vertex[3][9], Vertex[3][10], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[9]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> V, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> V[5, {Index[Gluon, 6]}], Field[7] -> 
       -F[3, {2, Index[Colour, 6]}], Field[8] -> F[3, {2, Index[Colour, 6]}], 
      Field[9] -> V[5, {Index[Gluon, 7]}], Field[10] -> 
       -F[3, {2, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][10], Field[5]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 6]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> -F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][10], Field[5]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> V, Field[9] -> V, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 6]}], 
      Field[7] -> -F[3, {2, Index[Colour, 6]}], 
      Field[8] -> V[5, {Index[Gluon, 6]}], Field[9] -> 
       V[5, {Index[Gluon, 7]}], Field[10] -> -F[4, {3, Index[Colour, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][10], Field[5]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][9], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 6]}], 
      Field[7] -> -F[4, {3, Index[Colour, 6]}], 
      Field[8] -> -F[3, {2, Index[Colour, 7]}], 
      Field[9] -> V[5, {Index[Gluon, 6]}], Field[10] -> 
       V[5, {Index[Gluon, 7]}]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][8], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][9], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][10], Field[5]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][10], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[8]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][8], Vertex[3][9], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> F, 
     Field[8] -> F, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 6]}], 
      Field[7] -> -F[4, {3, Index[Colour, 6]}], 
      Field[8] -> -F[3, {2, Index[Colour, 7]}], 
      Field[9] -> V[5, {Index[Gluon, 6]}], Field[10] -> 
       V[5, {Index[Gluon, 7]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[2, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {1, Index[Colour, 6]}], 
      Field[10] -> F[3, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {3, Index[Colour, 6]}], 
      Field[10] -> F[3, {3, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {1, Index[Colour, 6]}], 
      Field[10] -> F[4, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {2, Index[Colour, 6]}], 
      Field[10] -> F[4, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[2, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> U, Field[10] -> U] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -U[5, {Index[Gluon, 8]}], 
      Field[10] -> U[5, {Index[Gluon, 9]}]]], 
   FeynmanGraph[2, Generic == 3][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[2, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> V[5, {Index[Gluon, 8]}], 
      Field[10] -> V[5, {Index[Gluon, 9]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[3, {2, Index[Colour, 2]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[3, {2, Index[Colour, 6]}], Field[9] -> -F[3, {2, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[2, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {1, Index[Colour, 6]}], 
      Field[10] -> F[3, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {3, Index[Colour, 6]}], 
      Field[10] -> F[3, {3, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {1, Index[Colour, 6]}], 
      Field[10] -> F[4, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {2, Index[Colour, 6]}], 
      Field[10] -> F[4, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[2, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> U, Field[10] -> U] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -U[5, {Index[Gluon, 8]}], 
      Field[10] -> U[5, {Index[Gluon, 9]}]]], 
   FeynmanGraph[2, Generic == 3][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[2, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> V[5, {Index[Gluon, 8]}], 
      Field[10] -> V[5, {Index[Gluon, 9]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[3, {2, Index[Colour, 3]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[3, {2, Index[Colour, 6]}], Field[9] -> F[3, {2, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][8], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[2, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {1, Index[Colour, 6]}], 
      Field[10] -> F[3, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {3, Index[Colour, 6]}], 
      Field[10] -> F[3, {3, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {1, Index[Colour, 6]}], 
      Field[10] -> F[4, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {2, Index[Colour, 6]}], 
      Field[10] -> F[4, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[2, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> U, Field[10] -> U] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -U[5, {Index[Gluon, 8]}], 
      Field[10] -> U[5, {Index[Gluon, 9]}]]], 
   FeynmanGraph[2, Generic == 3][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[2, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> V[5, {Index[Gluon, 8]}], 
      Field[10] -> V[5, {Index[Gluon, 9]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][6], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][8], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> -F[4, {3, Index[Colour, 4]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       F[4, {3, Index[Colour, 6]}], Field[9] -> -F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][8], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][9], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[2, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> F, Field[10] -> F] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {1, Index[Colour, 6]}], 
      Field[10] -> F[3, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {2, Index[Colour, 6]}], 
      Field[10] -> F[3, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[3, {3, Index[Colour, 6]}], 
      Field[10] -> F[3, {3, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {1, Index[Colour, 6]}], 
      Field[10] -> F[4, {1, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {2, Index[Colour, 6]}], 
      Field[10] -> F[4, {2, Index[Colour, 7]}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -F[4, {3, Index[Colour, 6]}], 
      Field[10] -> F[4, {3, Index[Colour, 7]}]]], 
   FeynmanGraph[2, Generic == 2][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> U, Field[10] -> U] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> -U[5, {Index[Gluon, 8]}], 
      Field[10] -> U[5, {Index[Gluon, 9]}]]], 
   FeynmanGraph[2, Generic == 3][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> V, Field[9] -> V, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[2, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       V[5, {Index[Gluon, 7]}], Field[9] -> V[5, {Index[Gluon, 8]}], 
      Field[10] -> V[5, {Index[Gluon, 9]}]]]], 
 Topology[2][Propagator[Incoming][Vertex[1][1], Vertex[3][6], Field[1]], 
   Propagator[Outgoing][Vertex[1][2], Vertex[3][7], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][8], Field[4]], 
   Propagator[Outgoing][Vertex[1][5], Vertex[3][6], Field[5]], 
   Propagator[Internal][Vertex[3][6], Vertex[3][9], Field[6]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[7]], 
   Propagator[Internal][Vertex[3][8], Vertex[3][10], Field[8]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[9]], 
   Propagator[Loop[1]][Vertex[3][9], Vertex[3][10], Field[10]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> V[1], 
     Field[2] -> -F[3, {2, Index[Colour, 2]}], 
     Field[3] -> F[3, {2, Index[Colour, 3]}], 
     Field[4] -> -F[4, {3, Index[Colour, 4]}], 
     Field[5] -> F[4, {3, Index[Colour, 5]}], Field[6] -> F, Field[7] -> V, 
     Field[8] -> F, Field[9] -> F, Field[10] -> V] -> 
    Insertions[Particles][FeynmanGraph[1, Particles == 1][Field[1] -> V[1], 
      Field[2] -> -F[3, {2, Index[Colour, 2]}], 
      Field[3] -> F[3, {2, Index[Colour, 3]}], 
      Field[4] -> -F[4, {3, Index[Colour, 4]}], 
      Field[5] -> F[4, {3, Index[Colour, 5]}], 
      Field[6] -> F[4, {3, Index[Colour, 5]}], 
      Field[7] -> V[5, {Index[Gluon, 6]}], Field[8] -> 
       -F[4, {3, Index[Colour, 6]}], Field[9] -> F[4, {3, Index[Colour, 7]}], 
      Field[10] -> V[5, {Index[Gluon, 7]}]]]]]
